version: '3'

services:
  rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.7.4
      
  catalogue:
    container_name: catalogue
    build:
      context: ./src/Contexts
      dockerfile: catalogue/Dockerfile
    ports:
      - "8080:3000"
    command: npm run build
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq
    links:
      - rabbitmq
      - catalogue-db
  catalogue-db:
    container_name: catalogue-db
    build: ./src/Contexts/catalogue/app/db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=Catalogue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  auth-management:
    container_name: auth-management
    build:
      context: ./src/Contexts
      dockerfile: auth-management/Dockerfile
    ports:
      - "8081:3000"
    command: npm run build
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq
    links: 
      - rabbitmq
      - auth-db

  auth-db:
    container_name: auth-db
    build: ./src/Contexts/auth-management/app/db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=Auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  