version: '3'

services:


  rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.7.4



  inventory-management:
    container_name: inventory-management
    build:
      context: ./src/Contexts
      dockerfile: inventory-management/Dockerfile
    ports:
      - "8080:3000"
    command: npm run build
    environment:
      - PORT=3000
      - MESSAGE_BUS=amqp://rabbitmq
    links:
      - rabbitmq
      - inventory-db
  inventory-db:
    container_name: inventory-db
    build: ./src/Contexts/inventory-management/app/db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=Inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  #user-management:
  #  container_name: user-management
   # build:
    #  context: ./src/Contexts/user-management
    #  dockerfile: Dockerfile
    #ports:
    #  - "3001:3000"
    #environment:
    #  - PORT=3000
    #  - MESSAGE_BUS=amqp://rabbitmq
    #links: 
     #  - rabbitmq
  